name: release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Unit tests
        run: go test ./...

      - name: Check vet
        run: go vet ./...

  release:
    needs: test
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
          body: ${{steps.github_release.outputs.changelog}}