name: release

on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}