name: release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Unit tests
        run: go test ./...

      - name: Check vet
        run: go vet ./...

  release:
    needs: test
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}